### PR TITLE
views: Add census tract to SCAN encounters view

### PR DESCRIPTION
**Pull request by kairstenfay**
Mike recently informed us that the PI team agreed it is okay to add
census tract geocoding to the SCAN encounters view, provided we adhere
to previously defined aggregations for anything public.

See the following Slack message for more details:
https://seattle-flu-study.slack.com/archives/GV45P1162/p1591898955075200?thread_ts=1591217795.070100&cid=GV45P1162

### CODE REVIEW

**Comment by kairstenfay** [comment]
[Export census tract in SCAN view(s)](https://trello.com/c/rIOGXCT0/614-export-census-tract-in-scan-views)

**Comment by kairstenfay** [comment]
Pushed a fixup to add census tract to `shipping.hcov19_observation_v1`.

**Comment by tsibley** [comment]
Looks like changes from #109?

**Comment by kairstenfay** [comment]
> Looks like changes from #109?

Ah, yes. I was testing those changes locally and it looks like I forgot to revert them before creating this new branch.

**Comment by kairstenfay** [comment]
This should be fixed in the latest commit.

**Pull request merged**
