### PR TITLE
Row-level security for hCoV-19 results

### PR DESCRIPTION
**Pull request by tsibley**
Details in commit messages.

I tested this locally by doing:

```sh
export PGDATABASE=seattleflu

./dev/detect-rls-leaks  # should show no testable data error

psql -qAt service=seattleflu-restricted -qAt \
  <<<"select document::jsonb from receiving.presence_absence order by received" \
  | pipenv run id3c receiving upload presence_absence -

LOG_LEVEL=warning pipenv run id3c etl presence-absence --commit

./dev/detect-rls-leaks  # should show red not ok failures

sqitch deploy dev

./dev/detect-rls-leaks  # should show all ok (plus some permission denied warnings)
```

### CODE REVIEW

**Comment by tsibley** [comment]
[Row-level security for HCoV-19 results](https://trello.com/c/wDfOCJSK/359-row-level-security-for-hcov-19-results)

**Comment by tsibley** [comment]
Ah, one change I just realized still needs making is applying a policy or revokes to `receiving.presence_absence`.

**Comment by kairstenfay** [comment]
> ```psql -qAt service=seattleflu-restricted -qAt \
  <<<"select document::jsonb from receiving.presence_absence order by received" \
  | pipenv run id3c receiving upload presence_absence -```

I wish I had known I could do this when I was testing the RoR view for COVID-19 data!

**Comment by tsibley** [comment]
We should be able to do this for those tables too. I was just focused on the p/a results. Ok to do those as a separate change in the near future?

**Comment by joverlee521** [comment]
Yup! p/a results. are definitely more important right now, the genome changes can wait

**Pull request merged**
