### PR TITLE
Update UW reopening ETL to reflect Y3 study design

### PR DESCRIPTION
**Pull request by davereinhart**
In the Y3 HCT project, three instruments are being removed: `testing_determination_internal`, `husky_test_kit_registration`, and `kiosk_registration_4c7f`.  The `husky_test_kit_registration` instrument is being merged into `daily_attestation` form, using the same field names as before. 

Updating the ETL here to remove references to the old instruments and to use `daily_attestation` complete status and the presence of a `barcode_swabsend` value to indicate a dropbox kit.

### CODE REVIEW

**Comment by davereinhart** [comment]
After enrollments have been migrated to the new project (and confirmed all data is accounted for), the identifiers for enrollments should be updated on prod when this PR is deployed:
```
update warehouse.encounter 
set identifier = replace(identifier, 'https://hct.redcap.rit.uw.edu/45/', 'https://hct.redcap.rit.uw.edu/[new_project_number]/')
where identifier like 'https://hct.redcap.rit.uw.edu/45/%/enrollment_arm_1/'
```

**Comment by davereinhart** [comment]
[HCT Y3 Work](https://trello.com/c/yY6PJobF/1392-hct-y3-work)

**Review by bencap — APPROVED** [review]
lgtm assuming no further updates are needed

**Comment by davereinhart** [comment]
Deployed.

**Pull request merged**
