### PR TITLE
etl redcap_det_scan: add new questions from REDCap; shipping/views: new HCT daily_exposure value

### PR DESCRIPTION
**Pull request by davereinhart**
Update to include new REDCap questions added to SCAN IRB - English project on 2/2/2021:

- attend_event_jan2021
- indoor_facility
- social_precautions
- no_mask
- high_risk_feb2021

These questions have not been added to REDCap SCAN projects for other languages, but if they are it should not result in any further changes to this branch.

One deployed, will need to reingest records from 2/2/2021 to present to populate these values in ID3C.

This PR also includes a small change in a shipping view related to a new HCT daily_exposure value being requested. It was included here to avoid merge conflicts with sqitch files:
 - The survey team wants to add a yes_vac value to the daily_exposure question. In preparation for this shipping.__uw_encounters materialized view is updated to treat this new value the same as the current yes.

### CODE REVIEW

**Comment by geomapdev** [comment]
[Update HCT automation for new daily_exposure values](https://trello.com/c/kRckOOTu/1118-update-hct-automation-for-new-dailyexposure-values)

**Comment by geomapdev** [comment]
[Process new SCAN redcap questions](https://trello.com/c/rl88RNKz/1114-process-new-scan-redcap-questions)

**Review by kschwabefry — APPROVED** [review]
Changes look good to me by inspection. As discussed in slack, plan for the ETL will be to generate DETs for records after these questions were introduced in ~Feb, rather than bumping revision number.

**Comment by davereinhart** [comment]
Updated redcap_det_scan.py to add the 3 new checkbox questions to checkbox_fields list for pre-processing. Fully tested locally by re-ingesting REDCap data from 2/2/2021 on.

**Comment by davereinhart** [comment]
Rebased with master and re-implemented using new commits to avoid conflicts related to sqitch changes.

**Comment by davereinhart** [comment]
Deployed.

**Pull request merged**
