### PR TITLE
Locations

### PR DESCRIPTION
**Pull request by tsibley**
Supporting code for (the start of) our location catalog. Depends on seattleflu/id3c#56.

### CODE REVIEW

**Comment by tsibley** [comment]
Yep, should tag the sqitch schema. Good call!

**Comment by tsibley** [comment]
I also changed the sqitch change from `views` to `warehouse/views` since `shipping/views` was used by @kairstenfay and is now on master. I was thinking we'd collect all custom views into one change, but splitting by schema is fine too. (If we have inter-schema view dependencies later, we can merge the files then.)

**Comment by kairstenfay** [comment]
Oh, I didn't mean to start my own schema-dependent views organization. I mistakenly thought I was following what we did in `id3c`. Sorry about that.

**Comment by tsibley** [comment]
Really no worries. :-) Either way is good right now.

**Pull request merged**
