### PR TITLE
Remove Old Snomed Code From Target Table Definition

### PR DESCRIPTION
**Pull request by bencap**
We are now using a new Snomed code for Covid, under target 952. This change
removes the outdated target from the definition of the table. PA results
with this old target (789) were transitioned to the updated target (952).
When this sqitch change is deployed, we can also remove the outdated target
from the warehouse table and continue using 952 for future snomed cov targets.

### CODE REVIEW

**Comment by bencap** [comment]
Finishes QC cleanup needed from #321

**Comment by kschwabefry** [comment]
[Update hCoV-19 snomed code in warehouse.target](https://trello.com/c/cEcDzkCr/443-update-hcov-19-snomed-code-in-warehousetarget)

**Review by kschwabefry — APPROVED** [review]

**Comment by bencap** [comment]
Deployed via Sqitch.

**Comment by bencap** [comment]
Old target removed from table.

**Pull request merged**
