### PR TITLE
Convert NaN to Empty String Prior to Geocoding

### PR DESCRIPTION
**Pull request by bencap**
Geocoding expects either NoneType or String objects for address fields,
but NaN values were being sent to the geocoding function. This change
converts any NaNs in the parsed clinical records to empty strings before
geocoding so that the expected data type matches what is passed in.

### CODE REVIEW

**Review by kschwabefry — APPROVED** [review]
Thanks for the fix Ben. And good to fixup the lang vs lng too!!

**Review by davereinhart — COMMENTED** [review]
Can we check for values in the required fields before geocoding? It could get noisy if there are a lot of records missing addresses and it gets to this warning-level log:
https://github.com/seattleflu/id3c/blob/00bd7d051ff5c84befa83ec47ccc78ff40dd146a/lib/id3c/cli/command/geocode.py#L322

**Comment by bencap** [comment]
[PHSKC - Update clinical ETL to process PHSKC data - Part 2](https://trello.com/c/ho0gljgn/1282-phskc-update-clinical-etl-to-process-phskc-data-part-2)

**Comment by bencap** [comment]
Deployed.

**Pull request merged**
