### PR TITLE
Sfs ror

### PR DESCRIPTION
**Pull request by kairstenfay**
Create a new shipping view for SFS return of results (v3). Add the new UW Reopening barcode sets to it.

### CODE REVIEW

**Comment by kairstenfay** [comment]
[Update return of results workflow for UW Reopening](https://trello.com/c/ZEib91cE/762-update-return-of-results-workflow-for-uw-reopening)

**Review by joverlee521 — CHANGES_REQUESTED** [review]
Just a couple things missing:
1. Need add `drop view if exists shipping.return_results_v3;` to the revert script
2. Need to add `shipping.return_results_v3` to the verify script.

**Comment by kairstenfay** [comment]
> Just a couple things missing:
> 
>     1. Need add `drop view if exists shipping.return_results_v3;` to the revert script
> 
>     2. Need to add `shipping.return_results_v3` to the verify script.

Oh I didn't realize we were adding that to the revert script now. 
And thank you, I forgot about the verify script!

**Comment by kairstenfay** [comment]
> > Just a couple things missing:
> > ```
> > 1. Need add `drop view if exists shipping.return_results_v3;` to the revert script
> > 
> > 2. Need to add `shipping.return_results_v3` to the verify script.
> > ```
> 
> Oh I didn't realize we were adding that to the revert script now.
> And thank you, I forgot about the verify script!

Ah wait we need a way to drop the new view. No this makes sense entirely, it's just been so long since I've used sqitch!

**Comment by kairstenfay** [comment]
Fixed revert & verify scripts in latest push.

**Comment by tsibley** [comment]
Code looks good by inspection. Currently restoring a fresh copy of the database so I can dump the old view and new view and diff them to make sure that nothing has changed (for now).

**Comment by kairstenfay** [comment]
Rebased onto master.

**Comment by kairstenfay** [comment]
> Code looks good by inspection. Currently restoring a fresh copy of the database so I can dump the old view and new view and diff them to make sure that nothing has changed (for now).

Good call, thanks!

**Review by tsibley — APPROVED** [review]

**Pull request merged**
