### PR TITLE
Ingest result_value field for PHSKC samples

### PR DESCRIPTION
**Pull request by bencap**
This change allows the PHSKC ingestion pipeline to also ingest the `result_value` and `collect_ts` fields from the PHSKC data into the `presence_absence` table in ID3C.

Functionality was added that adds these fields to the fields that we extract from provided PHSKC sample metadata and parses it into ndjson files. Additionally, this change adds functions that generate FHIR compatible Observations and Diagnostic report resources which can be ingested into ID3C.

### CODE REVIEW

**Comment by bencap** [comment]
Note this change is intended to also ingest inconclusive samples, which are currently skipped by the ID3C ingestion pipeline for diagnostic resources. The change to ID3C [linked here](https://github.com/seattleflu/id3c/pull/302) allows for these inconclusive samples to be ingested.

**Comment by bencap** [comment]
[For PHSKC samples, add result_value to the columns we ingest.](https://trello.com/c/yj5B2B32/1371-for-phskc-samples-add-resultvalue-to-the-columns-we-ingest)

**Comment by bencap** [comment]
Testing Steps:
Pull down and checkout the branches in `id3c-customizations` and `id3c`. Navigate to `id3c-production` in `backoffice` and install both local repo versions. You then should copy down PHSKC excel data with something like:
```
rclone copy phskc-onedrive: . --ignore-case --include "2022-02_sfs_missing_metadata.xlsx"
```
and grab the aliquot data with something like the following:
```
envdir <path-to-bbi-aws-credentials> pipenv run id3c manifest parse-using-config etc/phskc-retrospectives-manifest.yaml > aliquot_data.ndjson
```

You can then refresh your cache and run the following sequence of commands to ingest PHSKC data:
```
PGSERVICE=seattleflu-local envdir ../env.d/smartystreets envdir ../env.d/deidentification pipenv run id3c clinical parse-phskc <path to excel data> <path to aliquot data> <path to sfs geocoding file> > <parsed data ndjson>
PGSERVICE=seattleflu-local pipenv run id3c clinical upload <parsed data ndjson>
PGSERVICE=seattleflu-local pipenv run id3c etl clinical --commit
PGSERVICE=seattleflu-local pipenv run id3c etl fhir --commit
```

Note in your local db instance you should have a new target with an identifier that looks something like `http://snomed.info/id/871562009`. Querying `presence_absence` with 
```
select * from warehouse.presence_absence where target_id = <target_id_from_above>
```
should return the results that were just ingested. 

You may also want to ensure the behavior of the UW Retrospectives sample ingestion is unchanged given changes to the way we handle inconclusive results in the `id3c` repo. These samples are dropped prior to the change, but we can verify by running through the pipeline with the following commands:
```
PGSERVICE=seattleflu-local envdir ../env.d/redcap pipenv run id3c redcap-det generate --api-url https://redcap.iths.org/api/ --project-id 19915 --include-incomplete > <uw_retro_dets>
PGSERVICE=seattleflu-local pipenv run id3c redcap-det upload <uw_retros_dets>
PGSERVICE=seattleflu-local envdir <redcap> envdir <deidentification> pipenv run id3c etl redcap-det uw-retrospectives --geocoding-cache <sfs-cache> --log-output
```

Note in your local db with the query
```
select count(*) from warehouse.presence_absence where target_id in (209, 210, 405, 788, 789, 787) where present is null
```
that we should not have any samples.

**Review by davereinhart — APPROVED** [review]

**Comment by bencap** [comment]
Deployed.

**Pull request merged**
